eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
server:
  port: 8888

spring:
  application:
    name: crbook-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fantast1211/crbook/tree
          username: fantast1211
          password: jm456852456
          default-label: master
          search-paths: config